@host = http://localhost:3000

@baseUrl = {{host}}/api/v1
@contentType = application/json

###
GET {{host}}
Content-Type: {{contentType}}

###
GET {{host}}/healthcheck
Content-Type: {{contentType}}

###
# @name createTodo
POST {{baseUrl}}/todos
Content-Type: {{contentType}}

{
    "task": "Ir ao mercado",
    "description": "Comprar leite, arroz, feijão"
}

###
# @name todos
GET {{baseUrl}}/todos?limit=10
Content-Type: {{contentType}}

###
GET {{baseUrl}}/todos/9fedc6f4-86c1-4315-b4aa-270716f29a7d
Content-Type: {{contentType}}

###
# @name updateTodo
PATCH {{baseUrl}}/todos/3dabd3be-568f-4d9b-b634-7bdf2e08ca90
Content-Type: {{contentType}}

{
    "isDone": "true",
    "doneAt": "2024-08-11T13:12:33.123Z"
}

###
# @name deleteTodo
DELETE {{baseUrl}}/todos/3dabd3be-568f-4d9b-b634-7bdf2e08ca90
Content-Type: {{contentType}}
