@host = http://localhost:8080 

@baseUrl = {{host}}/api/v1 

@contentType = application/json 

###
GET {{host}}
content-Type: {{contentType}}

###
GET {{host}}/healthcheck
content-Type: {{contentType}}

### 
POST {{baseUrl}}/todos
content-Type: {{contentType}}

{
  "task": "task to do", 
  "description": "aqui vai uma descricao"
}

### 
GET {{baseUrl}}/todos
content-Type: {{contentType}}

### 
GET {{baseUrl}}/todos/123
content-Type: {{contentType}}

### 
PATCH {{baseUrl}}/todos/123
content-Type: {{contentType}}

### 
DELETE {{baseUrl}}/todos/123
content-Type: {{contentType}}