services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - todo
    restart: always

  app:
    image: aws-ecs-fargate-nodejs-todo-app:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - todo
    restart: always

networks:
  todo:
